In [1]:
print("Hello, World!")

Hello, World!


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
print(np.__version__)

2.1.3


In [ ]:
l1 = [1, 2, 3, 4, 5]
#print(l1) This is only list 
l1

[1, 2, 3, 4, 5]

In [ ]:
x=np.array(l1)
print(x) # this is numpy array

[1 2 3 4 5]


In [7]:
#Create a 1D array
x= np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


que = find the difference between list and numpy array.

In [8]:
x=np.random.rand(5)
print(x)

[0.75079136 0.88350294 0.23685912 0.3143641  0.63102945]


In [11]:
x=np.random.randint(5,15,3)
print(x)

[13 11  9]


In [12]:
#2D array
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
y=np.random.rand(3,4)
print(y)

[[0.55704579 0.12232821 0.01483406 0.95080162]
 [0.80204098 0.34472441 0.49770709 0.68031651]
 [0.68504532 0.92539382 0.28277466 0.11581673]]


In [14]:
y=np.random.randint(5,16,(3,3))
print(y)

[[14 13  5]
 [ 7 14 12]
 [ 7 10 12]]


In [15]:
#3D array
z=np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
print(z)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]


In [16]:
a=np.zeros(((3,4)),dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
a=np.full((5,5),7)
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [19]:
a=np.eye(4,5,dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [20]:
print("shape of array:",a.shape)

shape of array: (4, 5)


In [21]:
z.ndim

4

In [22]:
a.size

20

In [23]:
a.dtype

dtype('int64')

In [25]:
x.min()

np.int32(9)

In [26]:
x.max()

np.int32(13)

In [27]:
x.argmin()

np.int64(2)

In [28]:
x.argmax()

np.int64(0)

In [29]:
x.mean()

np.float64(11.0)

In [34]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.sum()

np.int64(45)

In [39]:
a.sum()

np.int64(45)

indexing is the process of accessing a single element from a sequence using its position or index.

it reduce s single element at a specific position.

Slicing refers to the process of extracting a portion of an array or a subarray. It allow you to.

Access specific elements or range of elements in a Numpy array.

que = give a difference between indexing and Slicing.


In [40]:
x[-2]

np.int32(11)

In [41]:
x

array([13, 11,  9], dtype=int32)

In [42]:
x[-2]

np.int32(11)

In [43]:
y

array([[14, 13,  5],
       [ 7, 14, 12],
       [ 7, 10, 12]], dtype=int32)

In [44]:
y[0,2]

np.int32(5)

In [45]:
x[2:5]

array([9], dtype=int32)

In [47]:
x[:5]

array([13, 11,  9], dtype=int32)

In [48]:
x[:]

array([13, 11,  9], dtype=int32)

In [50]:
x[2]=100

In [51]:
x

array([ 13,  11, 100], dtype=int32)

In [52]:
x[1:8:2]

array([11], dtype=int32)

In [53]:
np.flip(x)

array([100,  11,  13], dtype=int32)

In [55]:
x[:]=200
x

array([200, 200, 200], dtype=int32)

In [1]:
# pandas 

import pandas as pd


pandas is an open-source librery for real world data analysis in python. it is bulid on top of numpy.

using pandas, data can be cleaned trasformed, manipulate, and analyzed.

series object series is a one dimensional labeled array. it supports different data type like integer, float , string etc...

a datafreams in pandas is a two-dimensional , tabular data structure similar to a spreadsheet or sql table.



In [2]:
s1 =  pd.Series([10,20,30,40,50])

In [3]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s2 = pd.Series([10,20,30,40,50],index=['A','B','C','D','E'])
s2

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [8]:
s1.values

array([10, 20, 30, 40, 50])

In [10]:
s2.values

array([10, 20, 30, 40, 50])

In [11]:
s2.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [12]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [15]:
data = [{'Name' : 'ABC' , 'Marks' : 28},
        {'Name' : 'EGF' , 'Marks' : 56},
        {'Name' : 'KHJ' , 'Marks' : 41},
        {'Name' : 'LKI' , 'Marks' : 56}]
f1=pd.DataFrame(data)
f1

Name  Marks
0  ABC     28
1  EGF     56
2  KHJ     41
3  LKI     56

In [16]:
data

[{'Name': 'ABC', 'Marks': 28},
 {'Name': 'EGF', 'Marks': 56},
 {'Name': 'KHJ', 'Marks': 41},
 {'Name': 'LKI', 'Marks': 56}]

In [17]:
f1

Name  Marks
0  ABC     28
1  EGF     56
2  KHJ     41
3  LKI     56

In [18]:
print(f1)

  Name  Marks
0  ABC     28
1  EGF     56
2  KHJ     41
3  LKI     56


In [19]:
type(f1)

pandas.core.frame.DataFrame

In [20]:
type(data)

list

In [28]:
iris =pd.read_csv('Iris.csv')

In [30]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [31]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [34]:
iris.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [44]:
cat = iris["Species"].unique()

In [45]:
cat

array(['setosa', 'versicolour', 'virginicaaa'], dtype=object)

In [37]:
iris.replace("Iris-setosa","setosa" , inplace=True)

In [40]:
iris.replace("Iris-versicolor","versicolour",inplace=True)

In [43]:
iris.replace("Iris-virginica","virginicaaa",inplace=True)

In [46]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [47]:
iris[['SepalLengthCm', 'SepalWidthCm']].head(10)

SepalLengthCm  SepalWidthCm
0            5.1           3.5
1            4.9           3.0
2            4.7           3.2
3            4.6           3.1
4            5.0           3.6
5            5.4           3.9
6            4.6           3.4
7            5.0           3.4
8            4.4           2.9
9            4.9           3.1

In [6]:
import pandas as pd

# Load dataset
iris = pd.read_csv("Iris.csv")

# Function
def yes_no(SepalLengthCm):
    return 'YES' if SepalLengthCm >= 5 else 'NO'

# Apply function
iris['Result'] = iris['SepalLengthCm'].apply(yes_no)

# Display output
print(iris.head())


   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa   
1   2            4.9           3.0            1.4           0.2  Iris-setosa   
2   3            4.7           3.2            1.3           0.2  Iris-setosa   
3   4            4.6           3.1            1.5           0.2  Iris-setosa   
4   5            5.0           3.6            1.4           0.2  Iris-setosa   

  Result  
0    YES  
1     NO  
2     NO  
3     NO  
4    YES  


In [8]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species', 'Result'],
      dtype='object')

In [9]:
iris.iloc[51:56]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
51  52            6.4           3.2            4.5           1.5   
52  53            6.9           3.1            4.9           1.5   
53  54            5.5           2.3            4.0           1.3   
54  55            6.5           2.8            4.6           1.5   
55  56            5.7           2.8            4.5           1.3   

            Species Result  
51  Iris-versicolor    YES  
52  Iris-versicolor    YES  
53  Iris-versicolor    YES  
54  Iris-versicolor    YES  
55  Iris-versicolor    YES

In [11]:
iris.drop('Result',axis=1,inplace=True)

In [12]:
iris.iloc[51:56,[2,5]]

SepalWidthCm          Species
51           3.2  Iris-versicolor
52           3.1  Iris-versicolor
53           2.3  Iris-versicolor
54           2.8  Iris-versicolor
55           2.8  Iris-versicolor

In [24]:
iris[iris['PetalLengthCm'] > 5]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
83    84            6.0           2.7            5.1           1.6   
100  101            6.3           3.3            6.0           2.5   
101  102            5.8           2.7            5.1           1.9   
102  103            7.1           3.0            5.9           2.1   
103  104            6.3           2.9            5.6           1.8   
104  105            6.5           3.0            5.8           2.2   
105  106            7.6           3.0            6.6           2.1   
107  108            7.3           2.9            6.3           1.8   
108  109            6.7           2.5            5.8           1.8   
109  110            7.2           3.6            6.1           2.5   
110  111            6.5           3.2            5.1           2.0   
111  112            6.4           2.7            5.3           1.9   
112  113            6.8           3.0            5.5           2.1   
114  115            5.8           2.8            5.1           2.4   
115  116            6.4           3.2            5.3           2.3   
116  117            6.5           3.0            5.5           1.8   
117  118            7.7           3.8            6.7           2.2   
118  119            7.7           2.6            6.9           2.3   
120  121            6.9           3.2            5.7           2.3   
122  123            7.7           2.8            6.7           2.0   
124  125            6.7           3.3            5.7           2.1   
125  126            7.2           3.2            6.0           1.8   
128  129            6.4           2.8            5.6           2.1   
129  130            7.2           3.0            5.8           1.6   
130  131            7.4           2.8            6.1           1.9   
131  132            7.9           3.8            6.4           2.0   
132  133            6.4           2.8            5.6           2.2   
133  134            6.3           2.8            5.1           1.5   
134  135            6.1           2.6            5.6           1.4   
135  136            7.7           3.0            6.1           2.3   
136  137            6.3           3.4            5.6           2.4   
137  138            6.4           3.1            5.5           1.8   
139  140            6.9           3.1            5.4           2.1   
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146            6.7           3.0            5.2           2.3   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

             Species  
83   Iris-versicolor  
100   Iris-virginica  
101   Iris-virginica  
102   Iris-virginica  
103   Iris-virginica  
104   Iris-virginica  
105   Iris-virginica  
107   Iris-virginica  
108   Iris-virginica  
109   Iris-virginica  
110   Iris-virginica  
111   Iris-virginica  
112   Iris-virginica  
114   Iris-virginica  
115   Iris-virginica  
116   Iris-virginica  
117   Iris-virginica  
118   Iris-virginica  
120   Iris-virginica  
122   Iris-virginica  
124   Iris-virginica  
125   Iris-virginica  
128   Iris-virginica  
129   Iris-virginica  
130   Iris-virginica  
131   Iris-virginica  
132   Iris-virginica  
133   Iris-virginica  
134   Iris-virginica  
135   Iris-virginica  
136   Iris-virginica  
137   Iris-virginica  
139   Iris-virginica  
140   Iris-virginica  
141   Iris-virginica  
142   Iris-virginica  
143   Iris-virginica  
144   Iris-virginica  
145   Iris-virginica  
147   Iris-virginica  
148   Iris-virginica  
149   Iris-virginica

In [26]:
iris[(iris['PetalLengthCm'] > 6) & (iris['Species'] == 'Iris-virginica')]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
105  106            7.6           3.0            6.6           2.1   
107  108            7.3           2.9            6.3           1.8   
109  110            7.2           3.6            6.1           2.5   
117  118            7.7           3.8            6.7           2.2   
118  119            7.7           2.6            6.9           2.3   
122  123            7.7           2.8            6.7           2.0   
130  131            7.4           2.8            6.1           1.9   
131  132            7.9           3.8            6.4           2.0   
135  136            7.7           3.0            6.1           2.3   

            Species  
105  Iris-virginica  
107  Iris-virginica  
109  Iris-virginica  
117  Iris-virginica  
118  Iris-virginica  
122  Iris-virginica  
130  Iris-virginica  
131  Iris-virginica  
135  Iris-virginica

In [28]:
iris.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [29]:

iris.duplicated().sum()

np.int64(0)

In [30]:
student =pd.read_csv('student_info.csv')

In [31]:
student

study_hours  student_marks
0           6.83          78.50
1           6.56          76.74
2            NaN          78.68
3           5.67          71.82
4           8.67          84.19
..           ...            ...
195         7.53          81.67
196         8.56          84.68
197         8.94          86.75
198         6.60          78.05
199         8.35          83.50

[200 rows x 2 columns]

In [32]:
student.columns

Index(['study_hours', 'student_marks'], dtype='object')

In [34]:
student.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   study_hours    195 non-null    float64
 1   student_marks  200 non-null    float64
dtypes: float64(2)
memory usage: 3.3 KB


In [35]:
student.tail()

study_hours  student_marks
195         7.53          81.67
196         8.56          84.68
197         8.94          86.75
198         6.60          78.05
199         8.35          83.50

In [36]:
student.head()

study_hours  student_marks
0         6.83          78.50
1         6.56          76.74
2          NaN          78.68
3         5.67          71.82
4         8.67          84.19

In [40]:
student.notnull().sum()

study_hours      195
student_marks    200
dtype: int64

In [45]:
student.isnull().sum()

study_hours      5
student_marks    0
dtype: int64

In [48]:
student['study_hours']=student['study_hours'].fillna(student['study_hours'].mean())

In [49]:
student.isnull().sum()

study_hours      0
student_marks    0
dtype: int64

In [50]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
iris = fetch_ucirepo(id=53) 
  
# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 
  
# metadata 
print(iris.metadata) 
  
# variable information 
print(iris.variables) 


{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org

In [1]:
pip install ucimlrepo

Note: you may need to restart the kernel to use updated packages.


In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
adult = fetch_ucirepo(id=2) 
  
# data (as pandas dataframes) 
X = adult.data.features 
y = adult.data.targets 
  
# metadata 
print(adult.metadata) 
  
# variable information 
print(adult.variables) 


{'uci_id': 2, 'name': 'Adult', 'repository_url': 'https://archive.ics.uci.edu/dataset/2/adult', 'data_url': 'https://archive.ics.uci.edu/static/public/2/data.csv', 'abstract': 'Predict whether annual income of an individual exceeds $50K/yr based on census data. Also known as "Census Income" dataset. ', 'area': 'Social Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 48842, 'num_features': 14, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Income', 'Education Level', 'Other', 'Race', 'Sex'], 'target_col': ['income'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1996, 'last_updated': 'Tue Sep 24 2024', 'dataset_doi': '10.24432/C5XW20', 'creators': ['Barry Becker', 'Ronny Kohavi'], 'intro_paper': None, 'additional_info': {'summary': "Extraction was done by Barry Becker from the 1994 Census database.  A set of reasonably clean records was extracted using the fol

In [5]:
X['workclass'].unique()

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked',
       nan], dtype=object)

In [14]:
X.loc[:,'workclass']=X['workclass'].fillna(X['workclass'].mode()[0])
X.loc[:,'native-country']=X['native-country'].fillna(X['native-country'].mode()[0])

In [16]:
X.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
dtype: int64

In [18]:
X.dropna()

age         workclass  fnlwgt  education  education-num  \
0       39         State-gov   77516  Bachelors             13   
1       50  Self-emp-not-inc   83311  Bachelors             13   
2       38           Private  215646    HS-grad              9   
3       53           Private  234721       11th              7   
4       28           Private  338409  Bachelors             13   
...    ...               ...     ...        ...            ...   
48837   39           Private  215419  Bachelors             13   
48838   64           Private  321403    HS-grad              9   
48839   38           Private  374983  Bachelors             13   
48840   44           Private   83891  Bachelors             13   
48841   35      Self-emp-inc  182148  Bachelors             13   

           marital-status         occupation    relationship  \
0           Never-married       Adm-clerical   Not-in-family   
1      Married-civ-spouse    Exec-managerial         Husband   
2                Divorced  Handlers-cleaners   Not-in-family   
3      Married-civ-spouse  Handlers-cleaners         Husband   
4      Married-civ-spouse     Prof-specialty            Wife   
...                   ...                ...             ...   
48837            Divorced     Prof-specialty   Not-in-family   
48838             Widowed     Prof-specialty  Other-relative   
48839  Married-civ-spouse     Prof-specialty         Husband   
48840            Divorced       Adm-clerical       Own-child   
48841  Married-civ-spouse    Exec-managerial         Husband   

                     race     sex  capital-gain  capital-loss  hours-per-week  \
0                   White    Male          2174             0              40   
1                   White    Male             0             0              13   
2                   White    Male             0             0              40   
3                   Black    Male             0             0              40   
4                   Black  Female             0             0              40   
...                   ...     ...           ...           ...             ...   
48837               White  Female             0             0              36   
48838               Black    Male             0             0              40   
48839               White    Male             0             0              50   
48840  Asian-Pac-Islander    Male          5455             0              40   
48841               White    Male             0             0              60   

      native-country  
0      United-States  
1      United-States  
2      United-States  
3      United-States  
4               Cuba  
...              ...  
48837  United-States  
48838  United-States  
48839  United-States  
48840  United-States  
48841  United-States  

[48842 rows x 14 columns]

In [19]:
X.dropna(inplace=True)

C:\Users\Hardyyy Soni\AppData\Local\Temp\ipykernel_16452\490656300.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.dropna(inplace=True)
