In [1]:
print("Hello, World!")

Hello, World!


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
print(np.__version__)

2.1.3


In [ ]:
l1 = [1, 2, 3, 4, 5]
#print(l1) This is only list 
l1

[1, 2, 3, 4, 5]

In [ ]:
x=np.array(l1)
print(x) # this is numpy array

[1 2 3 4 5]


In [7]:
#Create a 1D array
x= np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


que = find the difference between list and numpy array.

In [8]:
x=np.random.rand(5)
print(x)

[0.75079136 0.88350294 0.23685912 0.3143641  0.63102945]


In [11]:
x=np.random.randint(5,15,3)
print(x)

[13 11  9]


In [12]:
#2D array
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
y=np.random.rand(3,4)
print(y)

[[0.55704579 0.12232821 0.01483406 0.95080162]
 [0.80204098 0.34472441 0.49770709 0.68031651]
 [0.68504532 0.92539382 0.28277466 0.11581673]]


In [14]:
y=np.random.randint(5,16,(3,3))
print(y)

[[14 13  5]
 [ 7 14 12]
 [ 7 10 12]]


In [15]:
#3D array
z=np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
print(z)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]


In [16]:
a=np.zeros(((3,4)),dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
a=np.full((5,5),7)
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [19]:
a=np.eye(4,5,dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [20]:
print("shape of array:",a.shape)

shape of array: (4, 5)


In [21]:
z.ndim

4

In [22]:
a.size

20

In [23]:
a.dtype

dtype('int64')

In [25]:
x.min()

np.int32(9)

In [26]:
x.max()

np.int32(13)

In [27]:
x.argmin()

np.int64(2)

In [28]:
x.argmax()

np.int64(0)

In [29]:
x.mean()

np.float64(11.0)

In [34]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.sum()

np.int64(45)

In [39]:
a.sum()

np.int64(45)

indexing is the process of accessing a single element from a sequence using its position or index.

it reduce s single element at a specific position.

Slicing refers to the process of extracting a portion of an array or a subarray. It allow you to.

Access specific elements or range of elements in a Numpy array.

que = give a difference between indexing and Slicing.


In [40]:
x[-2]

np.int32(11)

In [41]:
x

array([13, 11,  9], dtype=int32)

In [42]:
x[-2]

np.int32(11)

In [43]:
y

array([[14, 13,  5],
       [ 7, 14, 12],
       [ 7, 10, 12]], dtype=int32)

In [44]:
y[0,2]

np.int32(5)

In [45]:
x[2:5]

array([9], dtype=int32)

In [47]:
x[:5]

array([13, 11,  9], dtype=int32)

In [48]:
x[:]

array([13, 11,  9], dtype=int32)

In [50]:
x[2]=100

In [51]:
x

array([ 13,  11, 100], dtype=int32)

In [52]:
x[1:8:2]

array([11], dtype=int32)

In [53]:
np.flip(x)

array([100,  11,  13], dtype=int32)

In [55]:
x[:]=200
x

array([200, 200, 200], dtype=int32)

In [1]:
# pandas 

import pandas as pd


pandas is an open-source librery for real world data analysis in python. it is bulid on top of numpy.

using pandas, data can be cleaned trasformed, manipulate, and analyzed.

series object series is a one dimensional labeled array. it supports different data type like integer, float , string etc...

a datafreams in pandas is a two-dimensional , tabular data structure similar to a spreadsheet or sql table.



In [2]:
s1 =  pd.Series([10,20,30,40,50])

In [3]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s2 = pd.Series([10,20,30,40,50],index=['A','B','C','D','E'])
s2

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [8]:
s1.values

array([10, 20, 30, 40, 50])

In [10]:
s2.values

array([10, 20, 30, 40, 50])

In [11]:
s2.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [12]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [15]:
data = [{'Name' : 'ABC' , 'Marks' : 28},
        {'Name' : 'EGF' , 'Marks' : 56},
        {'Name' : 'KHJ' , 'Marks' : 41},
        {'Name' : 'LKI' , 'Marks' : 56}]
f1=pd.DataFrame(data)
f1

Name  Marks
0  ABC     28
1  EGF     56
2  KHJ     41
3  LKI     56

In [16]:
data

[{'Name': 'ABC', 'Marks': 28},
 {'Name': 'EGF', 'Marks': 56},
 {'Name': 'KHJ', 'Marks': 41},
 {'Name': 'LKI', 'Marks': 56}]

In [17]:
f1

Name  Marks
0  ABC     28
1  EGF     56
2  KHJ     41
3  LKI     56

In [18]:
print(f1)

  Name  Marks
0  ABC     28
1  EGF     56
2  KHJ     41
3  LKI     56


In [19]:
type(f1)

pandas.core.frame.DataFrame

In [20]:
type(data)

list

In [28]:
iris =pd.read_csv('Iris.csv')

In [30]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [31]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [34]:
iris.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [44]:
cat = iris["Species"].unique()

In [45]:
cat

array(['setosa', 'versicolour', 'virginicaaa'], dtype=object)

In [37]:
iris.replace("Iris-setosa","setosa" , inplace=True)

In [40]:
iris.replace("Iris-versicolor","versicolour",inplace=True)

In [43]:
iris.replace("Iris-virginica","virginicaaa",inplace=True)

In [46]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [47]:
iris[['SepalLengthCm', 'SepalWidthCm']].head(10)

SepalLengthCm  SepalWidthCm
0            5.1           3.5
1            4.9           3.0
2            4.7           3.2
3            4.6           3.1
4            5.0           3.6
5            5.4           3.9
6            4.6           3.4
7            5.0           3.4
8            4.4           2.9
9            4.9           3.1

In [6]:
import pandas as pd

# Load dataset
iris = pd.read_csv("Iris.csv")

# Function
def yes_no(SepalLengthCm):
    return 'YES' if SepalLengthCm >= 5 else 'NO'

# Apply function
iris['Result'] = iris['SepalLengthCm'].apply(yes_no)

# Display output
print(iris.head())


   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa   
1   2            4.9           3.0            1.4           0.2  Iris-setosa   
2   3            4.7           3.2            1.3           0.2  Iris-setosa   
3   4            4.6           3.1            1.5           0.2  Iris-setosa   
4   5            5.0           3.6            1.4           0.2  Iris-setosa   

  Result  
0    YES  
1     NO  
2     NO  
3     NO  
4    YES  


In [8]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species', 'Result'],
      dtype='object')

In [9]:
iris.iloc[51:56]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
51  52            6.4           3.2            4.5           1.5   
52  53            6.9           3.1            4.9           1.5   
53  54            5.5           2.3            4.0           1.3   
54  55            6.5           2.8            4.6           1.5   
55  56            5.7           2.8            4.5           1.3   

            Species Result  
51  Iris-versicolor    YES  
52  Iris-versicolor    YES  
53  Iris-versicolor    YES  
54  Iris-versicolor    YES  
55  Iris-versicolor    YES

In [11]:
iris.drop('Result',axis=1,inplace=True)

In [12]:
iris.iloc[51:56,[2,5]]

SepalWidthCm          Species
51           3.2  Iris-versicolor
52           3.1  Iris-versicolor
53           2.3  Iris-versicolor
54           2.8  Iris-versicolor
55           2.8  Iris-versicolor